### ISSUE TITLE
Unable to bind to port 80 on WSL

### ISSUE THREAD

**Issue by burkeholland** [Azure/swa-emulator#46]
**Describe the bug**
When running the emulator in the WSL, an EACCESS error is thrown saying that permissions is denied on port 80. Inspection of the port with `lsof` will show that the port is free.

**To Reproduce**
1. Open a terminal instance in WSL on a SWA project
2. Run `swa`

![image](https://user-images.githubusercontent.com/686963/104519742-8e554700-55bf-11eb-846c-f86f58fce3ce.png)

**Expected behavior**
The emulator starts and is running on 0.0.0.0:80

**Desktop (please complete the following information):**
 - OS: Windows 10 v 19042.746
 - Version 0.0.1-alpha.7

**Comment by manekinekko** [comment]
Thanks for reporting this @burkeholland 

So the error you have is because ports below 1024 can be opened only by `root`. However, on macOS `swa` runs as expected and doesn't trigger this error. That's interesting! Can you try running `swa` as root, just to confirm that it's working correctly in WSL? (_we aren't going to recommend this_)

The only change I can suggest to avoid this, is to change the default port `80` to something else higher than 1024. 

Any thoughts @anthonychu @burkeholland ?

**Comment by anthonychu** [comment]
I agree with selecting a higher port.
